// Real end-to-end encryption, step 3 (docs/21-E2EE-TECHNICAL-DESIGN.md §1, §5)
//
// Production SodiumProvider, backed by react-native-libsodium (native
// module) for key generation, signing, and AEAD, and by `@noble/curves`/
// `@noble/hashes` (pure JS, audited, zero native deps — safe to add without
// a new native build) for X25519 Diffie-Hellman and HKDF-SHA256.
//
// SESSION 37 — a real, live, confirmed-catastrophic bug found and fixed
// here, not a hypothetical: this file used to call `sodium.crypto_
// scalarmult(...)` and `sodium._unstable_crypto_kdf_hkdf_sha256_extract/
// expand(...)` directly. Verified live against the actual installed
// react-native-libsodium (v1.7.0, the latest published version): its real
// native module — the `.native.js`/`.cpp` implementation Metro actually
// bundles for a device build, NOT the generic `lib/typescript/index.d.ts`
// this package points its own `package.json#types` field at, which is
// what `tsc` reads and why this compiled cleanly with zero type errors —
// does not implement `crypto_scalarmult` AT ALL (absent from both the
// native `.d.ts` and the `.cpp` source; grepped directly, zero matches).
// Every encrypted session bootstrap (X3DH) needs raw X25519 ECDH, with no
// substitute for it anywhere in this library's real API surface, so this
// call threw "undefined is not a function" the moment ANY user's first
// real on-device message through this path was attempted — which,
// confirmed via the live `e2ee_message_envelopes` table, had literally
// never happened before this fix: 0 rows, ever, despite the feature
// having shipped and been enabled on a real thread days earlier.
//
// Fix: `scalarMult` now uses `@noble/curves`'s pure-JS X25519
// implementation instead. Verified, not assumed, before wiring it in:
// (1) mutual DH agreement (Alice's shared secret == Bob's) holds; (2) a
// keypair generated by libsodium's own `crypto_box_keypair()` (still used
// here — a real, correctly-registered native function) produces the exact
// same public key AND the exact same DH output under `@noble/curves` as
// under `libsodium-wrappers-sumo`'s own `crypto_scalarmult` (the same
// underlying C library other builds of libsodium use) — proving key-format
// and computation compatibility, not just "the library runs." X25519 is a
// single standardized algorithm (RFC 7748); any two correct
// implementations must agree bit-for-bit, and this confirms both do.
//
// The `_unstable_` HKDF calls (real risk flagged by their own name, never
// actually vector-verified on-device per this file's prior header comment)
// are replaced too, on the same "don't trust an unverified native path
// when a verified one already exists in this codebase" principle — now
// using the exact same hand-rolled, RFC-5869/2104-vector-verified
// hkdfRfc5869.ts/hmacSha256Rfc2104.ts the Node test adapter already relies
// on (sodiumProviderTestAdapter.ts), fed by `@noble/hashes`'s pure-JS
// SHA-256 (verified against the standard NIST "abc" test vector) instead
// of `libsodium-wrappers-sumo`'s `crypto_hash_sha256` (Node-only, not
// available in react-native-libsodium either — confirmed absent from its
// exported function list the same way `crypto_scalarmult` was).

import sodium from 'react-native-libsodium';
import { x25519 } from '@noble/curves/ed25519.js';
import { sha256 } from '@noble/hashes/sha2.js';
import {
  hkdfExpand as hkdfExpandRfc5869,
  hkdfExtract as hkdfExtractRfc5869,
} from './hkdfRfc5869.ts';
import { hmacSha256 as hmacSha256Rfc2104 } from './hmacSha256Rfc2104.ts';
import type { KeyPair, SodiumProvider } from './sodiumProvider.ts';

function hmacSha256(key: Uint8Array, message: Uint8Array): Uint8Array {
  return hmacSha256Rfc2104(sha256, key, message);
}

// A THIRD real, live-confirmed gap in react-native-libsodium beyond the two
// in this file's own header comment: its AEAD encrypt/decrypt functions'
// `.d.ts` claims `additional_data` accepts `string | Uint8Array | null`,
// but the actual native-adapter JS (lib.native.js) only ever handles the
// `string` case — anything else throws "input type not yet implemented",
// confirmed live the moment this file's scalarMult/HKDF fix let a real
// on-device AEAD call be reached for the first time ever. This app's only
// AAD content (`associatedDataFor` in session.ts) is always a plain-ASCII
// string encoded to bytes via `TextEncoder`, so decoding it back is exactly
// lossless, not a lossy binary-to-text hack — this does NOT generalize to
// arbitrary binary AAD, which this native adapter cannot accept at all.
function aadToNativeString(aad: Uint8Array | null): string {
  return aad ? new TextDecoder().decode(aad) : '';
}

export const nativeSodiumProvider: SodiumProvider = {
  async ready() {
    await sodium.ready;
  },

  generateX25519KeyPair(): KeyPair {
    const { publicKey, privateKey } = sodium.crypto_box_keypair();
    return { publicKey, privateKey };
  },

  scalarMult(privateKey: Uint8Array, publicKey: Uint8Array): Uint8Array {
    return x25519.scalarMult(privateKey, publicKey);
  },

  generateEd25519KeyPair(): KeyPair {
    const { publicKey, privateKey } = sodium.crypto_sign_keypair();
    return { publicKey, privateKey };
  },

  sign(message: Uint8Array, privateKey: Uint8Array): Uint8Array {
    return sodium.crypto_sign_detached(message, privateKey);
  },

  verify(signature: Uint8Array, message: Uint8Array, publicKey: Uint8Array): boolean {
    return sodium.crypto_sign_verify_detached(signature, message, publicKey);
  },

  hkdfExtract(salt: Uint8Array, ikm: Uint8Array): Uint8Array {
    return hkdfExtractRfc5869(hmacSha256, salt, ikm);
  },

  hkdfExpand(prk: Uint8Array, info: string, length: number): Uint8Array {
    return hkdfExpandRfc5869(hmacSha256, prk, new TextEncoder().encode(info), length);
  },

  aeadEncrypt(
    plaintext: Uint8Array,
    aad: Uint8Array | null,
    nonce: Uint8Array,
    key: Uint8Array,
  ): Uint8Array {
    return sodium.crypto_aead_xchacha20poly1305_ietf_encrypt(
      plaintext,
      aadToNativeString(aad),
      null,
      nonce,
      key,
    );
  },

  aeadDecrypt(
    ciphertext: Uint8Array,
    aad: Uint8Array | null,
    nonce: Uint8Array,
    key: Uint8Array,
  ): Uint8Array {
    return sodium.crypto_aead_xchacha20poly1305_ietf_decrypt(
      null,
      ciphertext,
      aadToNativeString(aad),
      nonce,
      key,
    );
  },

  randomBytes(length: number): Uint8Array {
    return sodium.randombytes_buf(length);
  },
};
