/**
 * Privacy Policy — real content, not placeholder copy. Same drafting
 * posture as terms.ts: grounded in what this app actually collects, uses,
 * and shares, not generic language with the product name substituted in.
 * Written against the Nigeria Data Protection Act (NDPA) framework named
 * in docs/07-COMPLIANCE-LEGAL.md §5 — a draft for review, not a
 * substitute for qualified counsel confirming it against current NDPA
 * guidance before this ships publicly.
 *
 * Every specific claim here (what's hashed vs. stored raw, which vendors
 * see what, that there's no end-to-end encryption) is checked against
 * this session's own investigation of the actual schema/code, not
 * asserted generically — see docs/00-SESSION-HANDOFF.md session 13.
 */

import type { LegalSection } from './terms';

export const PRIVACY_LAST_UPDATED = '2026-09-15';

export const PRIVACY_POLICY: LegalSection[] = [
  {
    heading: '1. Who we are, and what this policy covers',
    body: [
      'This Privacy Policy explains how Sun Media Limited, a company registered in Nigeria ("Sun Media", "we", "us", "our"), collects, uses, shares, and protects information in connection with the InvolveMe mobile application (the "Service"). It should be read alongside our Terms of Service.',
    ],
  },
  {
    heading: '2. Information we collect',
    body: [
      'Account information: your phone number (used for one-time-passcode login and as your primary identifier), and any display name, avatar, or "about" status text you choose to add.',
      'Message and status content: the text of messages you send and status updates you post. Message content is stored so conversations can be delivered and displayed to their recipient — it is not end-to-end encrypted (see Section 9).',
      'Identity verification data: if you complete identity verification, we receive a verification result from our KYC provider and store the verified name it returns, plus a one-way cryptographic hash of your BVN or NIN (never the raw number itself — see Section 8 of our Terms).',
      'Payment and financial data: your credit purchase, spending, earning, transfer, and withdrawal history within the app, a tokenized reference to any bank account you link (not the raw account number, beyond what our payment provider needs to process a payout), and a provider-issued customer identifier from our payment processor.',
      'Device and fraud-prevention data: a one-way hash of a stable device identifier (computed on your device before it is ever sent to us — we never receive or store the raw hardware identifier), used to detect when multiple accounts share a device, as part of fraud prevention.',
      'Push notification data: a device push token, if you enable notifications, used solely to deliver notifications to your device.',
      'Usage and technical data: standard technical metadata generated by using a mobile app (such as timestamps of activity), used for security, fraud prevention, and operating the Service.',
    ],
  },
  {
    heading: '3. How we use your information',
    body: [
      'To provide the Service: deliver messages, display your profile to conversation partners, process top-ups, escrow releases, transfers, and withdrawals, and show you accurate balance and pricing information.',
      'For fraud and abuse prevention: to detect patterns consistent with wash-trading, collusion, spam/farming, or multi-accounting — including through device-fingerprint linkage, transaction-pattern analysis, and automated content moderation — and to enforce our Terms of Service.',
      'For identity verification and financial compliance: to meet Know-Your-Customer and anti-money-laundering obligations under Nigerian financial regulation before releasing withdrawals.',
      'For customer support: to respond to your requests, including account deletion requests.',
      'For legal compliance: to meet record-keeping, reporting, or disclosure obligations under applicable law.',
      'We do not use your information to serve third-party advertising, and we do not sell your personal information.',
    ],
  },
  {
    heading: '4. Our legal basis for processing your information',
    body: [
      'Under the Nigeria Data Protection Act, we process your information on the following bases: performance of a contract with you (delivering the Service you signed up for); compliance with a legal obligation (KYC/AML requirements, financial record-keeping); and our legitimate interests in operating a safe platform (fraud and abuse prevention, content moderation), balanced against your rights and interests.',
    ],
  },
  {
    heading: '5. Who we share information with',
    body: [
      'We share information with the following categories of third party, only as needed to provide the Service:',
      '• Payment processors (currently Flutterwave), to process top-ups and withdrawals. They receive the payment details necessary to process a transaction.',
      '• Identity verification providers (currently Prembly), to perform BVN/NIN verification. They receive the identity number you submit for verification and return a verification result and matched name to us; we do not store the number itself, only a hash.',
      '• Content moderation providers (currently OpenAI), which receive message and status text for automated screening as described in our Terms of Service, Section 11.',
      '• Push notification infrastructure (currently Expo), to deliver notifications to your device.',
      '• Law enforcement, courts, or regulators, where we are legally compelled to disclose information, or where necessary to investigate fraud or protect the rights and safety of our users.',
      'We do not sell your personal information to anyone, and we do not share it with third parties for their own independent marketing purposes.',
    ],
  },
  {
    heading: '6. How long we keep your information',
    body: [
      'While your account is active, we retain your information as needed to provide the Service. If you delete your account, we retain your financial and ledger transaction records for the period required by applicable Nigerian anti-money-laundering regulation, even though your profile information is deleted or anonymized at that point — this is a legal retention obligation we cannot waive on request, not a discretionary choice.',
      'Message content is retained for as long as the relevant conversation thread exists in the app, or until you or the other participant deletes your account (subject to the financial-record retention above for anything with a monetary consequence, such as a paid message’s billing record, which is distinct from the message text itself).',
    ],
  },
  {
    heading: '7. Your rights',
    body: [
      'Under the Nigeria Data Protection Act, you have the right to access the personal information we hold about you, request correction of inaccurate information, request deletion of your account (Section 13 of our Terms), and object to certain processing. To exercise these rights, contact us at the address in Section 13 below.',
      'Some rights are subject to the financial record-keeping obligations described in Section 6 — we cannot delete financial/ledger records we are legally required to retain, even at your request.',
    ],
  },
  {
    heading: '8. How we protect your information',
    body: [
      'Data is encrypted in transit between your device and our servers. Sensitive identifiers — your BVN/NIN and your device fingerprint — are never stored in raw form; only a one-way cryptographic hash is stored, computed with a secret value we control so the original value cannot practically be recovered from the hash.',
      'Access to financial and identity-verification data within our systems is restricted to what is operationally necessary. No system is perfectly secure, and we cannot guarantee absolute security, but we design our data handling around minimizing what raw sensitive data exists in the first place, not just protecting it after the fact.',
    ],
  },
  {
    heading: '9. No end-to-end encryption',
    body: [
      'InvolveMe does not currently offer end-to-end encryption for messages. Message content is encrypted in transit and stored on our servers, but — unlike some other messaging apps — Sun Media Limited has the technical ability to access message content, for example to investigate abuse reports, respond to legal process, or operate the content moderation described in Section 11 of our Terms. We are telling you this plainly rather than implying a level of privacy the Service does not currently provide.',
    ],
  },
  {
    heading: '10. Children’s privacy',
    body: [
      'The Service is not directed to, and may not be used by, anyone under 18 years old — see our Terms of Service, Section 2. We do not knowingly collect personal information from anyone under 18. If we become aware that an account belongs to someone under 18, we will suspend it.',
    ],
  },
  {
    heading: '11. International data transfers',
    body: [
      'Some of our infrastructure and service providers (including parts of our cloud database infrastructure and our content moderation provider) operate outside Nigeria. Where we transfer personal information outside Nigeria, we rely on the transfer mechanisms and safeguards recognized under the Nigeria Data Protection Act.',
    ],
  },
  {
    heading: '12. Changes to this policy',
    body: [
      'We may update this Privacy Policy from time to time. We will update the "last updated" date shown in the app when we do, and will highlight material changes in-app.',
    ],
  },
  {
    heading: '13. Contact',
    body: [
      'Questions about this Privacy Policy, or requests relating to your personal information, can be sent to support@sunmedialimited.com.ng.',
    ],
  },
];
