import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by `next dev`/`next build` and gitignored
    // — without this it locally fails lint the moment either has run, even
    // though the file is never committed. `out/` is `next build`'s static
    // export (output: 'export', the Cloudflare Pages deploy target) —
    // same reasoning, same gitignore entry, now that a real build produces
    // it locally for the first time.
    ignores: ['.next/**', 'out/**', 'node_modules/**', 'next-env.d.ts'],
  },
];

export default eslintConfig;
