// withCertPinning.js — TLS certificate pinning for the Supabase API host
// (docs/19-SECURITY-HARDENING-SCOPING.md §2.1/Tier B item 1). Pins at the
// OS level (Android Network Security Config, iOS ATS NSPinnedDomains) —
// deliberately NOT a JS library like `react-native-ssl-pinning` that
// replaces `fetch`, since @supabase/supabase-js and every other network
// call in this app already goes through the platform's native networking
// stack (OkHttp on Android, NSURLSession on iOS); pinning at that layer
// protects every request with zero JS-side code changes and zero new npm
// dependencies (rule #10, "stay lite" — `@expo/config-plugins` is already
// bundled with `expo` itself, not a new package).
//
// PIN TARGET, AND WHY IT'S ROOT-LEVEL, NOT LEAF-LEVEL — READ BEFORE EVER
// CHANGING THESE PINS:
//
// ekotjsmgfluufsoralmf.supabase.co is fronted by Cloudflare (confirmed via
// live `openssl s_client` + response headers, 2026-09-26), which issues its
// own TLS certificates — this app has zero contractual visibility into, or
// control over, Cloudflare's leaf-certificate rotation schedule. The live
// leaf cert observed at build time (issued by Google Trust Services "WE1")
// had a ~90-day validity window. Pinning to that leaf, or even to the
// specific intermediate ("WE1"), would require a new app-store release
// roughly every time Cloudflare rotates it — completely impractical, and a
// missed rotation means the app can no longer reach its own backend at all.
//
// Instead, this pins to the full set of Google Trust Services ROOT CAs
// (R1-R4, fetched directly from Google's own PKI repository, pki.goog,
// 2026-09-26) — root CAs are valid for decades and essentially never
// rotate. Pinning all four (not just the one seen live) hedges against
// Cloudflare/Google switching which specific Google root a future
// intermediate chains to, without this app needing to know or care which
// one is currently in use. This does NOT protect against Cloudflare
// switching to an entirely different CA vendor (e.g. Let's Encrypt,
// DigiCert) for this domain — a real residual risk given this is
// third-party infrastructure, not something InvolveMe operates. If that
// ever happens, Android fails open (see EXPIRATION below); iOS does not
// and would hard-fail every request to this host until a new build ships.
// Monitor Sentry for a spike in TLS/network failures specifically on iOS as
// the signal this has happened — it would look identical to a real outage
// otherwise.
//
// EXPIRATION (Android only — see PINS_EXPIRATION below): Android's Network
// Security Config supports a pin-set `expiration` date, after which
// Android stops enforcing pinning entirely (falls back to normal
// certificate validation — still secure, just not pinned) rather than
// failing every request. This is the safety valve for "we stopped paying
// attention to this and something changed" — set generously (about a year
// out) and treated as a real calendar reminder to re-verify and renew, not
// a deadline to let quietly lapse. iOS's NSPinnedDomains has no equivalent
// mechanism — there is no automatic fail-open on iOS, which is exactly why
// the pin set itself is deliberately broad (all 4 roots) rather than
// narrow.
//
// To regenerate/verify these pins later:
//   openssl s_client -connect ekotjsmgfluufsoralmf.supabase.co:443 \
//     -servername ekotjsmgfluufsoralmf.supabase.co -showcerts
//   (walk the chain to the root, then for the root of interest:)
//   openssl x509 -in root.pem -pubkey -noout \
//     | openssl pkey -pubin -outform DER \
//     | openssl dgst -sha256 -binary | openssl enc -base64

const { withAndroidManifest, withInfoPlist, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PINNED_DOMAIN = 'ekotjsmgfluufsoralmf.supabase.co';

// Google Trust Services root CAs R1-R4, SPKI SHA-256 pins, fetched directly
// from https://pki.goog/repo/certs/ (2026-09-26) — see this file's own
// header comment for why root-level, not leaf/intermediate.
const PINS_SHA256_BASE64 = [
  'hxqRlPTu1bMS/0DITB1SSu0vd4u/8l8TjPgfaAp63Gc=', // GTS Root R1
  'Vfd95BwDeSQo+NUYxVEEIlvkOlWY2SalKK1lPhzOx78=', // GTS Root R2
  'QXnt2YHvdHR3tJYmQIr0Paosp6t/nggsEGD4QJZ3Q0g=', // GTS Root R3
  'mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c=', // GTS Root R4 (the one actually observed live)
];

// Android-only fail-open date — see header comment. ~12 months out from
// when this was written (2026-09-26); treat as a real renewal reminder.
const PINS_EXPIRATION = '2027-09-26';

function buildNetworkSecurityConfigXml() {
  const pinEntries = PINS_SHA256_BASE64.map((p) => `      <pin digest="SHA-256">${p}</pin>`).join(
    '\n',
  );
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- @generated by plugins/withCertPinning.js — do not hand-edit; update the
     PINS_SHA256_BASE64/PINS_EXPIRATION constants in that file instead, the
     next prebuild regenerates this file from them. -->
<network-security-config>
  <domain-config>
    <domain includeSubdomains="false">${PINNED_DOMAIN}</domain>
    <pin-set expiration="${PINS_EXPIRATION}">
${pinEntries}
    </pin-set>
  </domain-config>
</network-security-config>
`;
}

function withCertPinningAndroid(config) {
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const xmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        buildNetworkSecurityConfigXml(),
      );
      return config;
    },
  ]);

  return withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application[0];
    application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return config;
  });
}

function withCertPinningIOS(config) {
  return withInfoPlist(config, (config) => {
    const existingAts = config.modResults.NSAppTransportSecurity || {};
    const existingPinnedDomains = existingAts.NSPinnedDomains || {};

    config.modResults.NSAppTransportSecurity = {
      ...existingAts,
      NSPinnedDomains: {
        ...existingPinnedDomains,
        [PINNED_DOMAIN]: {
          NSIncludesSubdomains: false,
          NSPinnedCAIdentities: PINS_SHA256_BASE64.map((pin) => ({
            'SPKI-SHA256-BASE64': pin,
          })),
        },
      },
    };

    return config;
  });
}

module.exports = function withCertPinning(config) {
  config = withCertPinningAndroid(config);
  config = withCertPinningIOS(config);
  return config;
};
